version : '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        tty: true
        restart: always
        volumes:
            - type: bind
              source: ./frontend/srcs
              target: /app
        ports:
            - 9778:9778
        
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        tty: true
        restart: always
        environment:
           - CLIENT_ID=${CLIENT_ID}
        volumes:
            - type: bind
              source: ./backend/srcs
              target: /server
        ports:
            - 3000:3000

